import os
from typing import TypedDict, List, Dict, Any, Optional
from langgraph.graph import StateGraph, END
from langchain_google_genai import ChatGoogleGenerativeAI
from api.v1.tools.vector_search import vector_search
from api.v1.tools.fts_search import fts_search
from api.v1.tools.hybrid_search import hybrid_search
from pydantic import BaseModel
from typing import Literal
from langchain_core.prompts import ChatPromptTemplate

llm = ChatGoogleGenerativeAI(
    model="gemini-3.1-pro-preview",
    temperature=0,
)


# binding llm with search tools
llm_with_tools = llm.bind_tools([
    vector_search,
    fts_search,
    hybrid_search,
])


# 1. State Definition
class GraphState(TypedDict):
    # User input
    original_query: str
    current_query: str

    # Query Validation / HyDE
    normalized_query: Optional[str]
    is_query_valid: Optional[bool]
    
    # "product" or "document" — set by router_node
    route: Optional[str]     

    # Loop control
    iteration_count: int
    max_iterations: int

    # Retrieval
    retrieval_strategy: Optional[str]
    retrieved_chunks: List[Dict[str, Any]]

    # Reranking
    reranked_chunks: List[Dict[str, Any]]

    # Validation
    is_relevant: Optional[bool]
    refined_query: Optional[str]

    # SQL generated by nl2sql_node                  
    generated_sql: Optional[str]
    sql_result: Optional[Any]

    # Final output
    final_answer: Optional[str]


# 2. Nodes definition
# Node 1: Query Validation Agent (HyDE-style)
def query_validation_agent(state: GraphState) -> GraphState:
    """
    Validates the user query and improves it if needed.
    Uses HyDE-style reasoning to produce a normalized, retrieval-ready query.
    """
    original_query = state["original_query"]

    system_prompt = (
        "You are a query validation agent.\n"
        "Determine whether the user's query is clear and specific enough "
        "to be used directly for retrieval or SQL generation.\n\n"
        "If the query is clear, respond with:\n"
        "VALID: <same query>\n\n"
        "If the query is vague or underspecified, first imagine a brief, ideal answer "
        "that would satisfy the user's intent, then rewrite the query in a clear, "
        "explicit, retrieval-ready form. Respond with:\n"
        "REWRITE: <improved query>\n"
    )

    response = llm.invoke(
        [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": original_query},
        ]
    )

    content = response.content.strip()

    if content.startswith("VALID:"):
        # Query is already good
        state["is_query_valid"] = True
        state["normalized_query"] = None
        state["current_query"] = original_query

    elif content.startswith("REWRITE:"):
        rewritten_query = content.replace("REWRITE:", "").strip()
        state["is_query_valid"] = False
        state["normalized_query"] = rewritten_query
        state["current_query"] = rewritten_query

    else:
        # Safety fallback: treat as valid
        state["is_query_valid"] = True
        state["normalized_query"] = None
        state["current_query"] = original_query

    return state

# ── Node 2: Router ────────────────────────────────────────────────────────────
# Uses Gemini (structured output) to classify the user's query.
#
# "product" → query is about products, prices, stock, orders, categories
#             → routes to nl2sql_node (PostgreSQL / agentic_rag_db)
# "document" → query is about policies, procedures, text documents
#             → routes to the RAG pipeline (vector_search → rerank → generate_answer)


class _RouteDecision(BaseModel):
    route: Literal["product", "document"]
    reason: str


def router_node(state: GraphState) -> GraphState:
    structured_llm = llm.with_structured_output(_RouteDecision)

    prompt = ChatPromptTemplate.from_messages([
        (
            "system",
            """You are a query router for an agentic RAG system.
            Classify the user's query into EXACTLY one of two routes:

            "product"  — the query asks about products, product prices, stock/inventory,
                        product categories, customer orders, order items, or anything
                        answerable from a structured e-commerce database with tables:
                        products, categories, orders, order_items.

            "document" — the query asks about policies, procedures, guidelines,
                        regulations, or any topic that requires reading text documents.

            Reply with the route and a one-sentence reason."""
        ),
        ("human", "Query: {current_query}")
    ])

    chain = prompt | structured_llm
    decision = chain.invoke({"current_query": state["current_query"]})
    print(f"[router_node] Route → '{decision.route}' | Reason: {decision.reason}")
    return {**state, "route": decision.route}


# ── Node NL2SQL: Translate query to SQL → Execute → Summarise ─────────────────
# Step 1  create_sql_query_chain generates a safe SELECT statement using the
#          live DB schema (table/column names + 2 sample rows per table).
# Step 2  SQLDatabase.run() executes the SQL on the read-only rag_readonly user.
#          Even if the LLM hallucinated a DML statement, the DB role blocks it.
# Step 3  Gemini summarises the raw results as a structured AIResponse.

def nl2sql_node(state: GraphState) -> GraphState:
    db = get_sql_database()

    # ── Step 1: Generate SQL using Gemini + live schema ─────────────────────
    schema_info = db.get_table_info()

    sql_prompt = ChatPromptTemplate.from_messages([
        (
            "system",
            """You are a PostgreSQL expert. Given the database schema below, 
            write a single valid SELECT query that answers the user's question.

            Rules:
            - Return ONLY the raw SQL — no explanation, no markdown fences, no backticks.
            - Use only the tables and columns present in the schema.
            - Do NOT generate INSERT, UPDATE, DELETE, DROP, or any DML/DDL statements.
            - Always add a LIMIT clause (max 50 rows) unless the question asks for aggregates.
            - For product or text searches: NEVER search for the full multi-word phrase as one
            ILIKE pattern. Instead, split the search into individual meaningful keywords
            and OR them together across both name and description columns.
            Example — user asks "wireless headset":
                WHERE (name ILIKE '%wireless%' OR description ILIKE '%wireless%')
                OR (name ILIKE '%headset%'  OR description ILIKE '%headset%')
                OR (name ILIKE '%headphones%' OR description ILIKE '%headphones%')
            Use your knowledge of synonyms (headset/headphones, laptop/notebook, etc.)
            to cast a wider net when the exact term may not match.

            Database schema:
            {schema}"""
        ),
        ("human", "Question: {question}")
    ])

    sql_chain = sql_prompt | llm
    raw_sql = sql_chain.invoke({
        "schema": schema_info,
        "question": state["current_query"]
    })
    # Gemini may return content as a list of parts or a plain string
    content = raw_sql.content
    if isinstance(content, list):
        content = "".join(
            p.get("text", "") if isinstance(p, dict) else str(p)
            for p in content
        )
    generated_sql = content.strip().strip("```").strip()
    if generated_sql.lower().startswith("sql"):
        generated_sql = generated_sql[3:].strip()
    print(f"[nl2sql_node] Generated SQL:\n{generated_sql}")

    # ── Step 2: Execute SQL ──────────────────────────────────────────────────
    try:
        sql_result: str = db.run(generated_sql)
    except Exception as exc:
        sql_result = f"SQL execution error: {exc}"
    print(f"[nl2sql_node] Raw result (truncated): {str(sql_result)[:200]}")

    # ── Step 3: Summarise into AIResponse ────────────────────────────────────
    structured_llm = llm.with_structured_output(AIResponse)
    answer_prompt = ChatPromptTemplate.from_messages([
        (
            "system",
            "You are a helpful data analyst. Answer the user's question using "
            "the SQL query results below. Be concise and format numbers/lists clearly. "
            "Set policy_citations to empty string, "
            "page_no to 'N/A', and document_name to 'agentic_rag_db'."
        ),
        (
            "human",
            "Question: {current_query}\n\n"
            "SQL Used:\n{sql}\n\n"
            "Query Results:\n{result}"
        )
    ])

    chain = answer_prompt | structured_llm
    answer = chain.invoke({
        "query": state["current_query"],
        "sql": generated_sql,
        "result": sql_result
    })
    print("[nl2sql_node] Answer generated.")
    response = answer.model_dump()
    response["policy_citations"] = "N/A"
    response["sql_query_executed"] = generated_sql
    return {
        **state,
        "generated_sql": generated_sql,
        "sql_result": str(sql_result),
        "final_answer": response
    }
    
# ── Node 3: Retrieval Agent with Tool Selection ─────────────────────────────
def retrieval_agent(state: GraphState) -> GraphState:
    """
    Retrieves documents for the current query.
    Dynamically selects vector, FTS, or hybrid (RRF) search using LLM tools.
    """
    query = state["current_query"]

    response = llm_with_tools.invoke(
        [
            {
                "role": "system",
                "content": (
                    "You are a retrieval agent. Choose the best search tool to retrieve documents "
                    "relevant to the given query. Here are the guidelines for when to use each search tool:\n"
                    "\n"
                    "1. **Vector Search** (Use when the query is semantic and requires retrieval of documents based on meaning):\n"
                    "   - Best suited for queries that are contextually rich and require understanding of word meaning, "
                    "   relationships between terms, and overall semantic similarity. For example:\n"
                    "   - Queries like 'Find research papers on AI language models' or 'What are the latest trends in data science?'\n"
                    "\n"
                    "2. **FTS (Full-Text Search)** (Use when the query is keyword-based and requires exact matching of terms):\n"
                    "   - Best suited for queries that involve direct keyword matching or when precision and relevance based on "
                    "   exact text content are required. For example:\n"
                    "   - Queries like 'Show me articles on machine learning algorithms' or 'What is the definition of neural networks?'\n"
                    "\n"
                    "3. **Hybrid Search (RRF - Reciprocal Rank Fusion)** (Use when combining both vector and FTS search results to maximize retrieval relevance):\n"
                    "   - Best used when the query is complex and requires a blend of semantic and exact keyword-based search. "
                    "   - Hybrid search fuses the results of both vector and FTS searches to improve overall relevance. For example:\n"
                    "   - Queries like 'What are the recent advancements in AI in healthcare?' or 'How does reinforcement learning work in robotics?'\n"
                    "\n"
                    "Your goal is to select the tool that will best retrieve relevant documents based on the provided query."
                ),
            },
            {"role": "user", "content": query},
        ]
    )

    if response.tool_calls:
        tool_call = response.tool_calls[0]
        tool_name = tool_call["name"]

        tool_fn_map = {
            "vector_search": vector_search,
            "fts_search": fts_search,
            "hybrid_search": hybrid_search,
        }

        results = tool_fn_map[tool_name](**tool_call["args"])

        state["retrieved_chunks"] = results
        state["retrieval_strategy"] = tool_name
    
    else:
        state["retrieved_chunks"] = []
        state["retrieval_strategy"] = None


    return state


# ── Node 4: Rerank ──────────────────────────────────────────────────────────────
# Uses Cohere's cross-encoder reranker.
# Unlike bi-encoders (which embed query and doc separately),
# a cross-encoder sees query + doc TOGETHER → more accurate relevance scoring.
def rerank_node(state: GraphState) -> GraphState:
    """
    Reranks retrieved chunks to improve relevance and precision.
    Produces a refined ordering of candidate documents.
    """
    co = cohere.ClientV2(api_key=os.getenv("COHERE_API_KEY"))
    docs = state["retrieved_chunks"]

    rerank_response = co.rerank(
        model="rerank-english-v3.0",
        query=state["current_query"],
        documents=[doc["content"] for doc in docs],
        top_n=10
    )

    # Map Cohere result indices back to LangChain Document objects
    reranked_docs = [docs[r.index] for r in rerank_response.results]

    print(f"[rerank_node] Top {len(reranked_docs)} chunks after reranking:")
    for i, r in enumerate(rerank_response.results):
        print(f"  Rank {i+1} | Cohere score: {r.relevance_score:.4f} | original index: {r.index}")

    return {**state, "reranked_chunks": reranked_docs}


# Node 5: Validation Agent ───────────────────────────────────────────────────
def validate_agent(state: GraphState) -> GraphState:
    """
    Validates whether the reranked chunks sufficiently answer the query.
    Triggers query refinement if relevance is insufficient.
    """
    query = state["current_query"]
    chunks = state.get("reranked_chunks", [])

    # Safety: no chunks means not relevant
    if not chunks:
        state["is_relevant"] = False
        state["iteration_count"] += 1
        state["refined_query"] = query
        return state
    
    if state["iteration_count"] >= state["max_iterations"]:
        state["is_relevant"] = True


    system_prompt = (
        "You are a relevance validation agent.\n"
        "Given a user query and retrieved information, decide whether the "
        "information is sufficient to answer the query.\n\n"
        "If the information is sufficient, respond with:\n"
        "RELEVANT\n\n"
        "If the information is insufficient, respond with:\n"
        "NOT_RELEVANT: <suggest a better refined query to retrieve better information>\n"
    )

    context = "\n\n".join(
        f"- {chunk['content'][:500]}"
        for chunk in chunks[:5]    # limit context to avoid token blow-up
    )

    response = llm.invoke(
        [
            {"role": "system", "content": system_prompt},
            {
                "role": "user",
                "content": f"Query:\n{query}\n\nRetrieved Information:\n{context}",
            },
        ]
    )

    verdict = response.content.strip()

    if verdict.startswith("RELEVANT"):
        state["is_relevant"] = True
        state["refined_query"] = None

    elif verdict.startswith("NOT_RELEVANT"):
        refined_query = verdict.replace("NOT_RELEVANT:", "").strip()

        state["is_relevant"] = False
        state["iteration_count"] += 1
        state["refined_query"] = refined_query
        state["current_query"] = refined_query

    else:
        # conservative fallback: accept as relevant
        state["is_relevant"] = True
        state["refined_query"] = None

    return state


# ── Node 6: Generate Answer ─────────────────────────────────────────────────
# Formats the top n reranked chunks as context and calls Gemini LLM.
# Uses structured output to enforce the AIResponse schema.

def generate_answer_agent(state: GraphState) -> GraphState:
    """
    Generates the final user-readable answer from validated knowledge.
    Formats and synthesizes the response.
    """
    structured_llm = llm.with_structured_output(AIResponse)

    context = "\n\n".join([
        f"[Source: {doc['metadata'].get('source', 'unknown')} | Page: {doc['metadata'].get('page', -1) + 1 if doc['metadata'].get('page') is not None else '?'}]\n{doc['content']}"
        for doc in state["reranked_chunks"]
    ])

    prompt = ChatPromptTemplate.from_messages([
        (
            "system",
            "You are a helpful assistant. Answer the user's question using only the "
            "provided context. Be precise and always cite the source document and page number."
        ),
        ("human", "Context:\n{context}\n\nQuestion: {query}")
    ])

    chain = prompt | structured_llm
    result = chain.invoke({"context": context, "query": state["current_query"]})

    print(f"[generate_answer_agent] Answer generated.")
    return {**state, "final_answer": result.model_dump()}
    

# Routing function
def should_retry_or_continue(state: GraphState) -> str:
    if (
        state["is_relevant"] is False
        and state["iteration_count"] < state["max_iterations"]
    ):
        return "retry"
    return "continue"


# Build the langGraph
def build_query_graph():
    graph = StateGraph(GraphState)

    # Nodes
    graph.add_node("query_validation", query_validation_agent)
    graph.add_node("router", router_node)
    graph.add_node("nl2sql", nl2sql_node)
    graph.add_node("retrieval", retrieval_agent)
    graph.add_node("rerank", rerank_node)
    graph.add_node("validate", validate_agent)
    graph.add_node("generate_answer", generate_answer_agent)

    # Entry point
    graph.set_entry_point("query_validation")

    # Linear flow
    graph.add_edge("query_validation", "router")
    graph.add_edge("retrieval", "rerank")
    graph.add_edge("rerank", "validate")

    graph.add_conditional_edges(
        "router",
        lambda s: s.get("route"),
        {
            "document": "retrieval",
            "product": "nl2sql",
            None: "retrieval"
        }
    )

    # Conditional loop
    graph.add_conditional_edges(
        "validate",
        should_retry_or_continue,
        {
            "retry": "retrieval",
            "continue": "generate_answer",
        },
    )

    # End
    graph.add_edge("generate_answer", END)
    graph.add_edge("nl2sql", END)

    return graph.compile()